"""Public API for the time-series causality toolkit.

This package exposes the reusable data-loading, preprocessing,
causal-analysis, and plotting utilities used by case studies and notebooks.
"""

from .causal_analysis import (
    compute_ccm,
    compute_dtw,
    compute_dtw_array,
    compute_te,
    extract_warping_path,
    granger_strength,
    print_parameter_sweep_report,
    run_granger_causality_report,
    sweep_ccm_convergence,
    sweep_ccm_convergence_steps,
    sweep_ccm_grid,
    sweep_ccm_grid_all,
    sweep_transfer_entropy,
    sweep_transfer_entropy_grid,
    warp_series_to_match,
)
from .data_loader import (
    LoadedSeriesPair,
    coerce_two_series,
    download_data,
    download_yfinance_series,
    get_ticker_name,
    load_two_series_from_csv,
)
from .plotting import (
    plot_ccm_convergence,
    plot_ccm_heatmap,
    plot_dtw_alignment,
    plot_granger_results,
    plot_line_trend,
    plot_parameter_heatmap,
    plot_preprocessing_results,
    plot_single_series,
    plot_series_comparison,
    plot_te_heatmap,
)
from .preprocessing import (
    PreprocessingConfig,
    PreprocessingResult,
    compute_log_returns,
    compute_returns,
    downsample_series,
    lagged_cross_correlation,
    lagged_cross_correlation_report,
    preprocess_series_pair,
    smooth_series,
    standardize_series,
    summarize_preprocessing,
)
from .stationarity import (
    adf_unit_root_test,
    make_series_stationary,
    print_adf_summary,
)
from .workflows import AnalysisConfig, PipelineConfig, run_analysis_pipeline, run_general_workflow, run_full_analysis_for_pair, run_preprocessing_flow, run_yfinance_demo

__all__ = [
    "adf_unit_root_test",
    "compute_ccm",
    "compute_dtw",
    "compute_dtw_array",
    "compute_log_returns",
    "compute_returns",
    "compute_te",
    "extract_warping_path",
    "AnalysisConfig",
    "LoadedSeriesPair",
    "coerce_two_series",
    "download_data",
    "download_yfinance_series",
    "downsample_series",
    "get_ticker_name",
    "granger_strength",
    "lagged_cross_correlation",
    "lagged_cross_correlation_report",
    "load_two_series_from_csv",
    "make_series_stationary",
    "plot_ccm_convergence",
    "plot_ccm_heatmap",
    "plot_dtw_alignment",
    "plot_granger_results",
    "plot_line_trend",
    "plot_parameter_heatmap",
    "plot_preprocessing_results",
    "plot_single_series",
    "plot_series_comparison",
    "plot_te_heatmap",
    "print_parameter_sweep_report",
    "print_adf_summary",
    "PipelineConfig",
    "PreprocessingConfig",
    "PreprocessingResult",
    "run_analysis_pipeline",
    "run_general_workflow",
    "run_full_analysis_for_pair",
    "run_preprocessing_flow",
    "run_granger_causality_report",
    "run_yfinance_demo",
    "preprocess_series_pair",
    "smooth_series",
    "standardize_series",
    "summarize_preprocessing",
    "sweep_ccm_convergence",
    "sweep_ccm_convergence_steps",
    "sweep_ccm_grid",
    "sweep_ccm_grid_all",
    "sweep_transfer_entropy",
    "sweep_transfer_entropy_grid",
    "warp_series_to_match",
]
